apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangout-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      appName: hangout
      version: "1.0"
  template:
    metadata:
      labels:
        appName: hangout
        version: "1.0"
    spec:
      containers:
        - name: hangout
          image: techsriman/hangout:1.0
          ports:
            - name: tomcatport
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /hangout/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /hangout/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3